language: scala
before_script: cd scala/anicolaspp/
scala:
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - sbt compile coverage test coverageReport
after_success:
  - pip install --user codecov && codecov
